# Generated by Django 4.2 on 2023-04-19 12:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtype',
            name='format',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='fieldtype',
            name='type',
            field=models.CharField(default='string', max_length=200),
        ),
    ]
