# Generated by Django 4.2 on 2023-04-19 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_fieldtype_format_fieldtype_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtype',
            name='max_length',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
