# Generated by Django 4.2 on 2023-04-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_fieldtype_max_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='slug_name',
            field=models.CharField(default='project_slug', max_length=20),
            preserve_default=False,
        ),
    ]
