# Generated by Django 4.2 on 2023-04-19 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0004_project_slug_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='asyncapi_version',
            field=models.CharField(default='2.6.0', max_length=20),
        ),
        migrations.AddField(
            model_name='service',
            name='description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='version',
            field=models.CharField(default='1.0.0', max_length=20),
        ),
    ]
