# Generated by Django 4.2 on 2023-04-19 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0005_service_asyncapi_version_service_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.CharField(default='Service description', max_length=1000),
        ),
    ]
