# Generated by Django 4.2 on 2023-04-19 23:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_alter_service_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='description',
            field=models.TextField(default='Service description', max_length=1000),
        ),
    ]
