# Generated by Django 4.2 on 2023-04-19 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    def delete_slug_names(apps, schema_editor):
        pass

    def update_slug_names(apps, schema_editor):
        service = apps.get_model("events", "Service")

        for obj in service.objects.all():
            obj.slug_name = obj.name.lower()
            obj.save()

    dependencies = [
        ('events', '0007_alter_service_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='slug_name',
            field=models.CharField(default="TBD", max_length=200),
        ),
        migrations.RunPython(update_slug_names, delete_slug_names)
    ]
