# Generated by Django 4.2 on 2023-04-19 23:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0008_service_slug_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='slug_name',
            field=models.CharField(max_length=200),
        ),
    ]
