# Generated by Django 4.2 on 2023-04-29 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0009_alter_service_slug_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='consumes',
            field=models.ManyToManyField(blank=True, null=True, related_name='event_consumers', to='events.event'),
        ),
        migrations.AlterField(
            model_name='service',
            name='publishes',
            field=models.ManyToManyField(blank=True, null=True, related_name='event_publishers', to='events.event'),
        ),
    ]
