# Generated by Django 4.2 on 2023-04-29 17:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0010_alter_service_consumes_alter_service_publishes'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrpcPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('syntax', models.CharField(default='proto3', max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='service',
            name='consumes',
            field=models.ManyToManyField(blank=True, related_name='event_consumers', to='events.event'),
        ),
        migrations.AlterField(
            model_name='service',
            name='publishes',
            field=models.ManyToManyField(blank=True, related_name='event_publishers', to='events.event'),
        ),
        migrations.CreateModel(
            name='GrpcService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.grpcpackage')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grpc_request', to='events.event')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grpc_response', to='events.event')),
            ],
        ),
        migrations.AddField(
            model_name='grpcpackage',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.service'),
        ),
    ]
