# Generated by Django 4.2 on 2023-04-30 08:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0011_grpcpackage_alter_service_consumes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grpcpackage',
            name='service',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='events.service'),
        ),
        migrations.AlterField(
            model_name='grpcservice',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grpc_request_payload', to='events.payload'),
        ),
        migrations.AlterField(
            model_name='grpcservice',
            name='response',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grpc_response_payload', to='events.payload'),
        ),
    ]
