# Generated by Django 4.2 on 2023-04-30 08:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0012_alter_grpcpackage_service_alter_grpcservice_request_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grpcservice',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grpc_request_payload', to='events.payload'),
        ),
        migrations.AlterField(
            model_name='grpcservice',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grpc_response_payload', to='events.payload'),
        ),
    ]
