# Generated by Django 4.2 on 2023-04-30 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0013_alter_grpcservice_request_alter_grpcservice_response'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtype',
            name='protobuf_type',
            field=models.CharField(default='string', max_length=200),
        ),
    ]
