# Generated by Django 4.2 on 2023-05-11 08:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0014_fieldtype_protobuf_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='grpcservice',
            name='request',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grpc_request_payload', to='events.payload', verbose_name='Request Payload'),
        ),
        migrations.AlterField(
            model_name='grpcservice',
            name='response',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='grpc_response_payload', to='events.payload', verbose_name='Response Payload'),
        ),
    ]
