# Generated by Django 4.2.1 on 2024-11-28 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0015_alter_grpcservice_request_alter_grpcservice_response'),
    ]

    operations = [
        migrations.CreateModel(
            name='DatabaseField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('required', models.BooleanField(default=False)),
                ('minimum', models.IntegerField(blank=True, null=True)),
                ('maximum', models.IntegerField(blank=True, null=True)),
                ('description', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='DatabasePayload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('create_rest', models.BooleanField(default=False)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.project')),
            ],
        ),
        migrations.CreateModel(
            name='DatabaseTables',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('slug_name', models.CharField(max_length=200)),
                ('description', models.TextField(default='Table description', max_length=1000)),
                ('fields', models.ManyToManyField(blank=True, related_name='table_fields', to='events.field')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.project')),
            ],
        ),
        migrations.RemoveField(
            model_name='grpcservice',
            name='package',
        ),
        migrations.RemoveField(
            model_name='grpcservice',
            name='request',
        ),
        migrations.RemoveField(
            model_name='grpcservice',
            name='response',
        ),
        migrations.AddField(
            model_name='event',
            name='is_sync',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='name',
            field=models.CharField(help_text='You can use [paramName] in name to pass parameters to event.', max_length=200),
        ),
        migrations.AlterField(
            model_name='event',
            name='response_payload',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='response_of_event', to='events.payload'),
        ),
        migrations.AlterField(
            model_name='service',
            name='asyncapi_version',
            field=models.CharField(default='3.0.0', max_length=20),
        ),
        migrations.DeleteModel(
            name='GrpcPackage',
        ),
        migrations.DeleteModel(
            name='GrpcService',
        ),
        migrations.AddField(
            model_name='databasefield',
            name='payload',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='events.databasepayload'),
        ),
        migrations.AddField(
            model_name='databasefield',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='events.fieldtype'),
        ),
        migrations.AddField(
            model_name='service',
            name='database_payloads',
            field=models.ManyToManyField(blank=True, related_name='service_payloads', to='events.databasepayload'),
        ),
    ]
