# Generated by Django 4.2.1 on 2024-12-18 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0016_databasefield_databasepayload_databasetables_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='endpoint',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
