# Generated by Django 4.2.1 on 2025-09-22 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0017_event_endpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='databasefield',
            name='default_value',
            field=models.TextField(blank=True, help_text='Default value for this field', null=True),
        ),
        migrations.AddField(
            model_name='databasefield',
            name='x_index',
            field=models.BooleanField(default=False, help_text='Whether this field is indexed'),
        ),
        migrations.AddField(
            model_name='databasefield',
            name='x_relation_schema_id',
            field=models.CharField(blank=True, help_text='Reference to another schema for relations', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='databasefield',
            name='x_type',
            field=models.CharField(blank=True, help_text='Database type (e.g., int64, string, boolean)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='databasefield',
            name='x_unique',
            field=models.BooleanField(default=False, help_text='Whether this field is unique'),
        ),
        migrations.AddField(
            model_name='databasepayload',
            name='x_derives_from',
            field=models.CharField(blank=True, help_text='Schema this derives from', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='databasepayload',
            name='x_parser_schema_id',
            field=models.CharField(blank=True, help_text='Parser schema ID', max_length=200, null=True),
        ),
    ]
