# Generated by Django 4.2.1 on 2025-09-25 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0018_databasefield_default_value_databasefield_x_index_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='databasefield',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order for display'),
        ),
        migrations.AddField(
            model_name='databasepayload',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order for display'),
        ),
        migrations.AddField(
            model_name='event',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order for display'),
        ),
        migrations.AddField(
            model_name='field',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order for display'),
        ),
        migrations.AddField(
            model_name='payload',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order for display'),
        ),
    ]
