# Generated by Django 4.2.1 on 2025-10-09 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0019_add_ordering_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='databasefield',
            name='order',
        ),
        migrations.RemoveField(
            model_name='databasepayload',
            name='order',
        ),
        migrations.RemoveField(
            model_name='event',
            name='order',
        ),
        migrations.RemoveField(
            model_name='field',
            name='order',
        ),
        migrations.RemoveField(
            model_name='payload',
            name='order',
        ),
        migrations.AddField(
            model_name='event',
            name='is_post',
            field=models.BooleanField(default=False, help_text='Whether this endpoint should use POST method'),
        ),
    ]
