# Generated by Django 4.2.1 on 2025-10-10 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0020_add_is_post_to_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='address',
            field=models.CharField(blank=True, help_text="Resource address for grouping channels (e.g., 'invoices', 'user')", max_length=200, null=True),
        ),
    ]
