# Generated by Django 4.2.1 on 2025-10-10 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0021_add_address_to_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='field',
            name='array_items_ref',
            field=models.CharField(blank=True, help_text='Schema reference for array items', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='array_items_type',
            field=models.CharField(blank=True, help_text='Type of array items', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='field',
            name='schema_ref',
            field=models.CharField(blank=True, help_text='Schema reference for complex types', max_length=200, null=True),
        ),
    ]
