# Generated by Django 4.2.1 on 2025-10-10 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0022_field_array_items_ref_field_array_items_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='summary',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='payload',
            name='description',
            field=models.TextField(blank=True, max_length=500, null=True),
        ),
    ]
