# Generated by Django 4.2.1 on 2025-11-18 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0023_event_description_event_summary_payload_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='x_general_name',
            field=models.CharField(blank=True, help_text='x-general-name from AsyncAPI YAML', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='x_service_name',
            field=models.CharField(blank=True, help_text='x-service-name from AsyncAPI YAML (kebab-case)', max_length=200, null=True),
        ),
    ]
