# Generated by Django 4.2.1 on 2025-11-18 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0024_add_x_general_name_x_service_name_to_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='original_title',
            field=models.CharField(blank=True, help_text='Original title from AsyncAPI YAML info section', max_length=500, null=True),
        ),
    ]
