# Generated by Django 4.2.1 on 2025-11-18 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0025_add_original_title_to_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtype',
            name='schema_definition',
            field=models.TextField(blank=True, help_text='Full JSON schema definition for complex object types', null=True),
        ),
    ]
