# Generated by Django 4.2.1 on 2026-02-12 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0027_add_service_to_databasepayload'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='is_jwt',
            field=models.BooleanField(default=False, help_text='Whether this endpoint requires JWT authentication'),
        ),
    ]
