# Generated by Django 4.2.1 on 2026-02-13 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0028_add_is_jwt_to_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='fieldtype',
            name='x_type',
            field=models.CharField(blank=True, help_text='Override for x-type in YAML', max_length=200, null=True),
        ),
    ]
