# Generated by Django 4.2.1 on 2026-04-29 12:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0029_add_x_type_to_fieldtype'),
    ]

    operations = [
        migrations.CreateModel(
            name='HTTPClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.AddField(
            model_name='databasefield',
            name='x_association_autocreate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='databasefield',
            name='x_association_autoupdate',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='databasefield',
            name='x_association_foreign_key',
            field=models.CharField(blank=True, help_text='Override FK column for association', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='databasefield',
            name='x_association_save_reference',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='databasefield',
            name='x_auto_create_time',
            field=models.BooleanField(default=False, help_text='Auto-set on insert'),
        ),
        migrations.AddField(
            model_name='databasefield',
            name='x_auto_increment',
            field=models.BooleanField(default=False, help_text='Auto-incrementing column'),
        ),
        migrations.AddField(
            model_name='databasefield',
            name='x_auto_update_time',
            field=models.BooleanField(default=False, help_text='Auto-set on update'),
        ),
        migrations.AddField(
            model_name='databasefield',
            name='x_cascade_delete',
            field=models.CharField(blank=True, help_text='e.g. SET NULL', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='databasefield',
            name='x_cascade_update',
            field=models.CharField(blank=True, help_text='e.g. CASCADE', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='databasefield',
            name='x_check',
            field=models.CharField(blank=True, help_text='CHECK constraint expression', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='databasefield',
            name='x_column',
            field=models.CharField(blank=True, help_text='Custom DB column name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='databasefield',
            name='x_comment',
            field=models.CharField(blank=True, help_text='DB column comment', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='databasefield',
            name='x_constraint',
            field=models.CharField(blank=True, help_text='Constraint name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='databasefield',
            name='x_embedded',
            field=models.BooleanField(default=False, help_text='Embed struct in parent'),
        ),
        migrations.AddField(
            model_name='databasefield',
            name='x_embedded_prefix',
            field=models.CharField(blank=True, help_text='Column name prefix for embedded struct', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='databasefield',
            name='x_foreign_key',
            field=models.CharField(blank=True, help_text='FK column name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='databasefield',
            name='x_ignore',
            field=models.BooleanField(default=False, help_text='Marks field as gorm:"-" (not persisted)'),
        ),
        migrations.AddField(
            model_name='databasefield',
            name='x_join_foreign_key',
            field=models.CharField(blank=True, help_text='M2M FK column', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='databasefield',
            name='x_join_references',
            field=models.CharField(blank=True, help_text='M2M ref column', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='databasefield',
            name='x_join_table',
            field=models.CharField(blank=True, help_text='Junction table name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='databasefield',
            name='x_many_to_many',
            field=models.CharField(blank=True, help_text='M2M link table identifier', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='databasefield',
            name='x_not_null',
            field=models.BooleanField(default=False, help_text='NOT NULL constraint'),
        ),
        migrations.AddField(
            model_name='databasefield',
            name='x_nullable',
            field=models.BooleanField(default=False, help_text='Allow NULL explicitly'),
        ),
        migrations.AddField(
            model_name='databasefield',
            name='x_polymorphic',
            field=models.CharField(blank=True, help_text='Polymorphic type field name', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='databasefield',
            name='x_polymorphic_value',
            field=models.CharField(blank=True, help_text="This model's polymorphic value", max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='databasefield',
            name='x_precision',
            field=models.IntegerField(blank=True, help_text='Decimal precision', null=True),
        ),
        migrations.AddField(
            model_name='databasefield',
            name='x_references',
            field=models.CharField(blank=True, help_text='Referenced column', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='databasefield',
            name='x_scale',
            field=models.IntegerField(blank=True, help_text='Decimal scale', null=True),
        ),
        migrations.AddField(
            model_name='databasefield',
            name='x_serializer',
            field=models.CharField(blank=True, help_text='GORM serializer tag (e.g., json)', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='databasefield',
            name='x_size',
            field=models.IntegerField(blank=True, help_text='Column max character length', null=True),
        ),
        migrations.AddField(
            model_name='databasefield',
            name='x_type_override',
            field=models.CharField(blank=True, help_text='SQL type override (e.g., varchar(32))', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='databasefield',
            name='x_unique_index',
            field=models.BooleanField(default=False, help_text='Unique index (composite uniqueness)'),
        ),
        migrations.AddField(
            model_name='service',
            name='x_transport',
            field=models.CharField(blank=True, choices=[('rest', 'REST'), ('grpc', 'gRPC'), ('both', 'Both')], help_text='x-transport: rest | grpc | both', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='databasepayload',
            name='service',
            field=models.ForeignKey(help_text='Service that owns this database object', on_delete=django.db.models.deletion.CASCADE, to='events.service'),
        ),
        migrations.CreateModel(
            name='HTTPClientField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='events.httpclient')),
            ],
        ),
        migrations.AddField(
            model_name='httpclient',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='http_clients', to='events.service'),
        ),
        migrations.CreateModel(
            name='GRPCClient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grpc_clients', to='events.service')),
            ],
        ),
        migrations.CreateModel(
            name='DbOperation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('block', 'block'), ('unblock', 'unblock'), ('delete-by-field', 'delete-by-field'), ('update', 'update')], max_length=50)),
                ('schema', models.CharField(help_text='Target DB schema name (e.g. DB_user)', max_length=200)),
                ('lookup_field', models.CharField(max_length=200)),
                ('lookup_field_2', models.CharField(blank=True, help_text='Second lookup field for composite queries', max_length=200, null=True)),
                ('status', models.CharField(blank=True, help_text='Status value to set (for block type)', max_length=200, null=True)),
                ('function_name', models.CharField(blank=True, help_text='Override generated function name', max_length=200, null=True)),
                ('event', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='db_operation', to='events.event')),
            ],
        ),
    ]
