# Generated by Django 4.2.1 on 2026-04-29 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0030_httpclient_databasefield_x_association_autocreate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='x_service_ip',
            field=models.CharField(blank=True, help_text='x-service-ip placeholder for deployment config', max_length=100, null=True),
        ),
    ]
