# Generated by Django 4.2.1 on 2026-04-29 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0031_add_service_x_service_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='databasepayload',
            name='description',
            field=models.TextField(blank=True, help_text='Schema description', null=True),
        ),
    ]
